sudo: required
services:
  - docker
language: node_js
node_js:
  - "4.3"
before_script:
  - docker-compose -f docker-compose.test.yml up -d dynamodbtest
  - sleep 5
script:
  - make test
cache:
  directories:
  - node_modules
install:
  - npm install
