sudo: required
services:
  - docker
language: node_js
node_js:
  - "4.3"
script:
  - docker-compose -f docker-compose.test.yml run test
cache:
  directories:
  - node_modules
install:
  - npm install
