npm:
    extends:
        file: ./docker-compose.yml
        service: node
    entrypoint: ['npm']

serverless:
  extends:
    file: ./docker-compose.yml
    service: node
  environment:
     - SLS_DEBUG=OK
     - SERVERLESS_ENV=invoke
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
  links:
    - dynamodb
  ports:
    - 3000:3000
  entrypoint: ['node_modules/serverless/bin/serverless']

dynamodb:
  image: deangiberson/aws-dynamodb-local
  ports:
    - 8000:8000

deploy:
  extends:
    file: ./docker-compose.yml
    service: node
  environment:
     - SERVERLESS_ENV=deploy
     - AWS_ACCESS_KEY_ID
     - AWS_SECRET_ACCESS_KEY
  ports:
    - 3000:3000
  entrypoint: node_modules/serverless/bin/serverless deploy
