node:
  image: node:4.3
  volumes:
    - .:/app
  working_dir: /app

webpack-dev-server:
  extends:
    file: ./docker-compose.yml
    service: node
  environment:
    BABEL_ENV: browser
  ports:
    - 3001:3001
  command: node node_modules/webpack-dev-server/bin/webpack-dev-server.js --port 3001 --host 0.0.0.0

serverless-dev-server:
  extends:
    file: ./docker-compose.yml
    service: node
  environment:
    SLS_DEBUG: OK
  links:
    - dynamodb
  ports:
    - 3000:3000
  command: node_modules/serverless/bin/serverless webpack serve --port 3000 --host 0.0.0.0

dynamodb:
  image: deangiberson/aws-dynamodb-local
  ports:
    - 8000:8000
