server:
  image: cannin/nodejs-http-server
  volumes:
    - ./src/frontend:/public
  working_dir: /public
  ports:
    - 8080:8080

node:
  image: node:4.1.2
  volumes:
    - .:/app
  working_dir: /app

devserver:
  extends:
    file: ./docker-compose.yml
    service: node
  environment:
    - BABEL_ENV=browser
  ports:
    - 3001:3001
  command: node node_modules/webpack-dev-server/bin/webpack-dev-server.js --port 3001 --host 0.0.0.0
