version: '2'
services:
    npm:
        extends:
            file: ./docker-compose.yml
            service: node
        entrypoint: ['npm']

    serverless:
        extends:
            file: ./docker-compose.yml
            service: node
        environment:
            - SLS_DEBUG=OK
            - SERVERLESS_ENV=invoke
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - AWS_DYNAMODB_ENDPOINT=http://localhost:8000
            - OCTOPUSH_USER_LOGIN
            - OCTOPUSH_API_KEY
            - OCTOPUSH_SIMULATION=OK
            - REPORT_LINK
            - LOG=ok
        network_mode: "host"
        entrypoint: ['node_modules/serverless/bin/serverless']

    deploy:
        extends:
            file: ./docker-compose.yml
            service: node
        environment:
            - SERVERLESS_ENV=deploy
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - OCTOPUSH_USER_LOGIN
            - OCTOPUSH_API_KEY
            - REPORT_LINK
            - LOG=ok
        entrypoint: node_modules/serverless/bin/serverless deploy

    serve:
        image: cannin/nodejs-http-server
        volumes:
            - ./build:/public
            - ./node_modules:/public/node_modules
        working_dir: /public
        ports:
            - 8080:8080
